### ISSUE TITLE
fix: Bot gets stuck in non-existent voice channel

### ISSUE THREAD

**Issue by kyleyannelli** [kyleyannelli/KMusicBot#91]
Bot will get stuck in a non-existent voice channel. It is unclear how this initiates, but it ends in a constant disconnecting loop where the bots disconnect timer keeps attempting to remove the null session. Possible memory leak and will need to invoke the behavior while monitoring memory & stack.

**Comment by kyleyannelli** [comment]
Was unable to replicate this issue, will leave open  for 2 more weeks just in case

**Comment by kyleyannelli** [comment]
Possible cause?
```
6279138169716736, name: r/BAND CHASERS), sessionId: 0aeb5ed588e4298cf730c3db7a57aaea, endpoint: us-east853.discord.media:443)! {shard=0}
2023-12-11 06:02:55.870+0000 ERROR org.javacord.core.util.event.EventDispatcherBase Unhandled exception in a listener thread for MONEY SPREADERS! {shard=0}
 java.lang.NullPointerException
        at java.base/java.util.ArrayList.<init>(ArrayList.java:179)
        at dev.kmfg.musicbot.core.lavaplayer.ProperTrackScheduler.getFullAudioQueue(ProperTrackScheduler.java:143)
        at dev.kmfg.musicbot.core.lavaplayer.LavaSource.getAudioQueue(LavaSource.java:249)
        at dev.kmfg.musicbot.core.sessions.AudioSession.toString(AudioSession.java:228)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at dev.kmfg.musicbot.core.sessions.AudioSession.shutdown(AudioSession.java:244)
        at dev.kmfg.musicbot.core.listenerhandlers.UserLeaveVoiceListenerHandler.disconnectFromEmptyServerVoiceChannel(UserLeaveVoiceListenerHandler.java:69)
        at dev.kmfg.musicbot.core.listenerhandlers.UserLeaveVoiceListenerHandler.onServerVoiceChannelMemberLeave(UserLeaveVoiceListenerHandler.java:52)
        at org.javacord.core.util.event.EventDispatcher.lambda$dispatchServerVoiceChannelMemberLeaveEvent$199(EventDispatcher.java:6720)
        at org.javacord.core.util.event.EventDispatcherBase.lambda$dispatchEvent$12(EventDispatcherBase.java:215)
        at org.javacord.core.util.event.EventDispatcherBase.lambda$checkRunningListenersAndStartIfPossible$20(EventDispatcherBase.java:289)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        ```

**Comment by kyleyannelli** [comment]
Commit bede0b109a9f2742fa2301fe00a00827122d44ba should help investigate above claim. Adds logging and null checks in the root of the above null pointer.

**Comment by kyleyannelli** [comment]
I think the null pointer was causing further down code to not execute and cause sessions to not be removed. This no longer seems to be an issue now that the null check is in place.
